# Generated by Django 3.2.7 on 2021-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_catphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catphoto',
            options={'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='catphoto',
            name='photo',
            field=models.ImageField(upload_to='cat_photos'),
        ),
    ]
