# Generated by Django 3.2.7 on 2021-09-18 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('author', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 9, 18, 15, 34, 51, 929025))),
            ],
        ),
    ]
