# Generated by Django 3.2.7 on 2021-09-16 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=datetime.datetime(2011, 11, 4, 0, 5, 23)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 12, 5, 8, 315893)),
        ),
    ]
