# Generated by Django 3.2.7 on 2021-09-18 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 17, 35, 27, 920751)),
        ),
    ]
